stages:
  - linting
  - security-analysis
  - docker

linting:
  stage: linting
  image: python:3.10
  script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
    - pip install flake8
    - flake8 --exclude=venv

security-analysis:
  stage: security-analysis
  image: python:3.10
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install bandit
    - bandit -r app.py
    - bandit -r config.py
  allow_failure: true

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t readthat .
