version: '3'

services:
  app:
    build: .
    environment:
      DATABASE_NAME: readthat
      DATABASE_HOST: db
      DATABASE_USER: user-readthat
      DATABASE_PASS: super-secure-pw
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: user-readthat
      MYSQL_PASSWORD: super-secure-pw
      MYSQL_ROOT_PASSWORD: db_password_root
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql