version: '3'

services:
  app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_username
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: db_password_root
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d